# Generated by Django 4.1.7 on 2023-03-11 18:58

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('vacancyType', models.CharField(choices=[('Undefined', 'Undefined'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], default='Undefined', max_length=10)),
                ('education', models.CharField(choices=[('No', 'No'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'Phd')], default='Bachelors', max_length=10)),
                ('experience', models.CharField(choices=[('No', 'No'), ('1 year', 'One Year'), ('3 years', 'Three Years'), ('5 years above', 'Five Years')], default='No', max_length=20)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('positions', models.IntegerField(default=1)),
                ('last_date', models.DateTimeField(default=datetime.datetime(2023, 3, 26, 18, 58, 42, 871846))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
