# Generated by Django 4.1.7 on 2023-04-08 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_last_date_alter_vacancy_vacancytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 21, 34, 36, 552113)),
        ),
    ]
